project_id = "qayywyddbprlhkqcqllf"

[functions.razorpay]
verify_jwt = false

[functions.contact-notification]
verify_jwt = false

[functions.cron-executor]
verify_jwt = false

[functions.admin-otp]
verify_jwt = false

[functions.admin-setup]
verify_jwt = false

[functions.security-alert]
verify_jwt = false

[functions.location-confirmation]
verify_jwt = false

[functions.mapbox-token]
verify_jwt = false

[functions.family-photo-url]
verify_jwt = true

[functions.new-device-alert]
verify_jwt = false

[functions.ops-health]
verify_jwt = false

[functions.ops-openapi]
verify_jwt = false

[functions.ops-swagger]
verify_jwt = false

[functions.admin-webauthn]
verify_jwt = false
